#pragma once


#define SERIAL_UART1_PORT	    GPIOB
#define SERIAL_UART1_PORT_RCC	RCC_AHB1Periph_GPIOB
#define SERIAL_UART1_RX_PIN	    GPIO_Pin_7
#define SERIAL_UART1_TX_PIN	    GPIO_Pin_6
#define SERIAL_UART1_RX_SOURCE	GPIO_PinSource7
#define SERIAL_UART1_TX_SOURCE	GPIO_PinSource6

#define SERIAL_UART3_PORT	    GPIOD
#define SERIAL_UART3_PORT_RCC	RCC_AHB1Periph_GPIOD
#define SERIAL_UART3_RX_PIN	    GPIO_Pin_9
#define SERIAL_UART3_TX_PIN	    GPIO_Pin_8
#define SERIAL_UART3_RX_SOURCE	GPIO_PinSource9
#define SERIAL_UART3_TX_SOURCE	GPIO_PinSource8

#define SERIAL_UART4_PORT	    GPIOA
#define SERIAL_UART4_PORT_RCC	RCC_AHB1Periph_GPIOA
#define SERIAL_UART4_RX_PIN	    GPIO_Pin_1
#define SERIAL_UART4_TX_PIN	    GPIO_Pin_0
#define SERIAL_UART4_RX_SOURCE	GPIO_PinSource1
#define SERIAL_UART4_TX_SOURCE	GPIO_PinSource0

#define SERIAL_UART6_PORT	    GPIOC
#define SERIAL_UART6_PORT_RCC	RCC_AHB1Periph_GPIOC
#define SERIAL_UART6_RX_PIN	    GPIO_Pin_7
#define SERIAL_UART6_TX_PIN	    GPIO_Pin_6
#define SERIAL_UART6_RX_SOURCE	GPIO_PinSource7
#define SERIAL_UART6_TX_SOURCE	GPIO_PinSource6

#define SERIAL_UART7_PORT	    GPIOE
#define SERIAL_UART7_PORT_RCC	RCC_AHB1Periph_GPIOE
#define SERIAL_UART7_RX_PIN	    GPIO_Pin_7
#define SERIAL_UART7_TX_PIN	    GPIO_Pin_8
#define SERIAL_UART7_RX_SOURCE	GPIO_PinSource7
#define SERIAL_UART7_TX_SOURCE	GPIO_PinSource8


